import React from 'react'

const  Skills = () => {
  return (
    <div><h1>Skills</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae esse aspernatur porro earum fuga labore voluptatibus deserunt! Itaque accusamus quae magni delectus a repudiandae fugit error reiciendis perspiciatis distinctio beatae at quos magnam quis aut animi rem nemo harum, cumque veniam iste, nobis laudantium? Quas magnam vero aperiam. Earum velit rerum doloribus inventore rem vel deserunt blanditiis. Quibusdam illum nostrum, rem ratione ab, officia sed facere eligendi dolores vitae consectetur repudiandae impedit adipisci necessitatibus cum inventore totam nobis blanditiis. Quas nulla omnis quo cum vero reiciendis quaerat corrupti facere magnam dicta laboriosam deserunt provident amet itaque excepturi neque est, sunt officia molestiae exercitationem harum fugit quisquam. Quasi aperiam exercitationem quo, odit recusandae aspernatur repellat earum nulla dolor corporis ipsa saepe velit distinctio, ratione quam accusantium obcaecati est amet ex consectetur tempora suscipit quos beatae? Asperiores quidem iusto quibusdam, modi molestias sint assumenda enim illum error tenetur accusantium culpa earum nemo iste. Magnam recusandae quidem libero. Iste officia eos consectetur odit nostrum illo explicabo provident quibusdam, impedit dolores consequuntur eius nisi voluptate ut vero hic voluptates, cumque inventore quas quos tempora repellendus sit aliquam. Amet libero, delectus sint blanditiis vero aliquid eos officiis eaque error consectetur, eveniet totam ducimus. Quis soluta doloremque aut earum, provident incidunt expedita veritatis doloribus amet dolores asperiores? Odio eaque aliquid cum officiis optio deleniti porro quod odit, maxime, fugit nostrum iusto corrupti soluta! Quam repudiandae sunt omnis iure consectetur provident totam est facere ad incidunt qui, molestiae dolores placeat tenetur. Corporis voluptatem excepturi aliquid a at neque, libero accusantium eum repellat, tempore beatae modi asperiores culpa omnis sint, fugit quidem? Natus alias minima autem sapiente minus debitis tempore, odit adipisci. Molestias sed accusamus magni. Ea minima voluptatem id perferendis quod perspiciatis nam libero officiis? Earum illum animi eius nostrum, odit culpa nesciunt adipisci aliquam. Nostrum, animi!</p>
    </div>
  )
}

export default  Skills